# Generated by Django 3.2.3 on 2022-07-28 12:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('subject_name', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'subject',
                'db_table': 'subject',
            },
        ),
        migrations.CreateModel(
            name='SubjectScores',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('score', models.IntegerField()),
                ('subject_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject', to='Subjects.subject')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Users_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'subject_scores',
                'db_table': 'subject_scores',
            },
        ),
    ]
